const dummmyData = [{
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-07T05:10:54Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-07T05:11:07Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "test",
        "first_name": "Minato",
        "id": 32,
        "last_name": "Namakaze",
        "staff_id": 8,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T11:35:54Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": "four",
        "checkout_mode": "",
        "checkout_time": false,
        "checkout_type": "",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": false,
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 31,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T11:22:51Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": "three",
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T11:35:46Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "seven",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 30,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T11:22:04Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": "second",
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T11:22:19Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "six",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 29,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T11:16:42Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": "first checkin",
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T11:21:17Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "five ",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 28,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T10:59:50Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T11:04:00Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "fourth ",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 27,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T10:56:25Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T10:59:48Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "third ",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 26,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T10:56:05Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T10:56:21Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "second",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 25,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": false,
        "checkin_mode": "Remote",
        "checkin_time": "2021-08-06T10:50:44Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": false,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-08-06T10:56:02Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": false,
        "checkout_user_comments": "first check",
        "first_name": "tamilmani.sarangapani@qmofi.com",
        "id": 24,
        "last_name": false,
        "staff_id": 4,
        "status": "pending"
    },
    {
        "admin_comments": "Test",
        "checkin_mode": "Remote",
        "checkin_time": "2021-07-31T03:37:00Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": true,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-07-31T08:40:00Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": true,
        "checkout_user_comments": false,
        "first_name": "vijay",
        "id": 23,
        "last_name": "venkatesh",
        "staff_id": 3,
        "status": "approved"
    },
    {
        "admin_comments": "Te",
        "checkin_mode": "Remote",
        "checkin_time": "2021-07-29T03:30:00Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": true,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-07-29T05:30:00Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": true,
        "checkout_user_comments": false,
        "first_name": "vijay",
        "id": 21,
        "last_name": "venkatesh",
        "staff_id": 3,
        "status": "approved"
    },
    {
        "admin_comments": "",
        "checkin_mode": "Remote",
        "checkin_time": "2021-07-28T19:30:00Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": true,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-07-28T21:32:00Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": true,
        "checkout_user_comments": false,
        "first_name": "vijay",
        "id": 22,
        "last_name": "venkatesh",
        "staff_id": 3,
        "status": "approved"
    },
    {
        "admin_comments": "",
        "checkin_mode": "Remote",
        "checkin_time": "2021-07-28T03:30:00Z",
        "checkin_type": "Manual",
        "checkin_updated_by_admin": true,
        "checkin_user_comments": false,
        "checkout_mode": "Remote",
        "checkout_time": "2021-07-28T11:30:00Z",
        "checkout_type": "Manual",
        "checkout_updated_by_admin": true,
        "checkout_user_comments": false,
        "first_name": "vijay",
        "id": 20,
        "last_name": "venkatesh",
        "staff_id": 3,
        "status": "approved"
    }
]

module.exports = dummmyData